// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package sqlc

import (
	"context"
)

const getCatalogItems = `-- name: GetCatalogItems :many
SELECT id, title, description, disabled
FROM catalog
ORDER BY title
`

func (q *Queries) GetCatalogItems(ctx context.Context) ([]Catalog, error) {
	rows, err := q.db.Query(ctx, getCatalogItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Catalog
	for rows.Next() {
		var i Catalog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
