// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: data.sql

package sqlc

import (
	"context"
)

const saveData = `-- name: SaveData :exec
INSERT INTO data (key, value)
VALUES ($1, $2)
`

type SaveDataParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SaveData(ctx context.Context, arg SaveDataParams) error {
	_, err := q.db.Exec(ctx, saveData, arg.Key, arg.Value)
	return err
}
