// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetCatalogItems(ctx context.Context) ([]Catalog, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	SaveData(ctx context.Context, arg SaveDataParams) error
}

var _ Querier = (*Queries)(nil)
