// Code generated by ogen, DO NOT EDIT.
package v1

type GetCatalogRes interface {
	getCatalogRes()
}

type GetMeRes interface {
	getMeRes()
}

type LoginRes interface {
	loginRes()
}

type LogoutRes interface {
	logoutRes()
}

type PostDataRes interface {
	postDataRes()
}
