// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"time"

	"github.com/google/uuid"
)

// Ref: #/components/schemas/CatalogItem
type CatalogItem struct {
	ID          OptUUID   `json:"id"`
	Title       OptString `json:"title"`
	Description OptString `json:"description"`
	Disabled    OptBool   `json:"disabled"`
}

// GetID returns the value of ID.
func (s *CatalogItem) GetID() OptUUID {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *CatalogItem) GetTitle() OptString {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *CatalogItem) GetDescription() OptString {
	return s.Description
}

// GetDisabled returns the value of Disabled.
func (s *CatalogItem) GetDisabled() OptBool {
	return s.Disabled
}

// SetID sets the value of ID.
func (s *CatalogItem) SetID(val OptUUID) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *CatalogItem) SetTitle(val OptString) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *CatalogItem) SetDescription(val OptString) {
	s.Description = val
}

// SetDisabled sets the value of Disabled.
func (s *CatalogItem) SetDisabled(val OptBool) {
	s.Disabled = val
}

type CookieAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *CookieAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *CookieAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *CookieAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *CookieAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/DataRequest
type DataRequest struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GetKey returns the value of Key.
func (s *DataRequest) GetKey() string {
	return s.Key
}

// GetValue returns the value of Value.
func (s *DataRequest) GetValue() string {
	return s.Value
}

// SetKey sets the value of Key.
func (s *DataRequest) SetKey(val string) {
	s.Key = val
}

// SetValue sets the value of Value.
func (s *DataRequest) SetValue(val string) {
	s.Value = val
}

// GetCatalogInternalServerError is response for GetCatalog operation.
type GetCatalogInternalServerError struct{}

func (*GetCatalogInternalServerError) getCatalogRes() {}

type GetCatalogOKApplicationJSON []CatalogItem

func (*GetCatalogOKApplicationJSON) getCatalogRes() {}

// GetCatalogUnauthorized is response for GetCatalog operation.
type GetCatalogUnauthorized struct{}

func (*GetCatalogUnauthorized) getCatalogRes() {}

// GetMeInternalServerError is response for GetMe operation.
type GetMeInternalServerError struct{}

func (*GetMeInternalServerError) getMeRes() {}

// GetMeUnauthorized is response for GetMe operation.
type GetMeUnauthorized struct{}

func (*GetMeUnauthorized) getMeRes() {}

// LoginInternalServerError is response for Login operation.
type LoginInternalServerError struct{}

func (*LoginInternalServerError) loginRes() {}

// Ref: #/components/schemas/LoginRequest
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetEmail returns the value of Email.
func (s *LoginRequest) GetEmail() string {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *LoginRequest) GetPassword() string {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *LoginRequest) SetEmail(val string) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *LoginRequest) SetPassword(val string) {
	s.Password = val
}

// LoginUnauthorized is response for Login operation.
type LoginUnauthorized struct{}

func (*LoginUnauthorized) loginRes() {}

// LogoutInternalServerError is response for Logout operation.
type LogoutInternalServerError struct{}

func (*LogoutInternalServerError) logoutRes() {}

// LogoutOK is response for Logout operation.
type LogoutOK struct{}

func (*LogoutOK) logoutRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// PostDataCreated is response for PostData operation.
type PostDataCreated struct{}

func (*PostDataCreated) postDataRes() {}

// PostDataInternalServerError is response for PostData operation.
type PostDataInternalServerError struct{}

func (*PostDataInternalServerError) postDataRes() {}

// PostDataUnauthorized is response for PostData operation.
type PostDataUnauthorized struct{}

func (*PostDataUnauthorized) postDataRes() {}

// Ref: #/components/schemas/User
type User struct {
	ID        OptUUID     `json:"id"`
	Email     OptString   `json:"email"`
	CreatedAt OptDateTime `json:"created_at"`
}

// GetID returns the value of ID.
func (s *User) GetID() OptUUID {
	return s.ID
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() OptString {
	return s.Email
}

// GetCreatedAt returns the value of CreatedAt.
func (s *User) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *User) SetID(val OptUUID) {
	s.ID = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val OptString) {
	s.Email = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *User) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

func (*User) getMeRes() {}
func (*User) loginRes() {}
