// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetCatalog implements getCatalog operation.
//
// Get catalog items.
//
// GET /api/v1/catalog
func (UnimplementedHandler) GetCatalog(ctx context.Context) (r GetCatalogRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMe implements getMe operation.
//
// Get current user info.
//
// GET /api/v1/auth/me
func (UnimplementedHandler) GetMe(ctx context.Context) (r GetMeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// Authenticate user.
//
// POST /api/v1/auth/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginRequest) (r LoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// Log out user.
//
// POST /api/v1/auth/logout
func (UnimplementedHandler) Logout(ctx context.Context) (r LogoutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PostData implements postData operation.
//
// Post some data.
//
// POST /api/v1/data
func (UnimplementedHandler) PostData(ctx context.Context, req *DataRequest) (r PostDataRes, _ error) {
	return r, ht.ErrNotImplemented
}
