// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	GetCatalogOperation OperationName = "GetCatalog"
	GetMeOperation      OperationName = "GetMe"
	LoginOperation      OperationName = "Login"
	LogoutOperation     OperationName = "Logout"
	PostDataOperation   OperationName = "PostData"
)
