// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetCatalog implements getCatalog operation.
	//
	// Get catalog items.
	//
	// GET /api/v1/catalog
	GetCatalog(ctx context.Context) (GetCatalogRes, error)
	// GetMe implements getMe operation.
	//
	// Get current user info.
	//
	// GET /api/v1/auth/me
	GetMe(ctx context.Context) (GetMeRes, error)
	// Login implements login operation.
	//
	// Authenticate user.
	//
	// POST /api/v1/auth/login
	Login(ctx context.Context, req *LoginRequest) (LoginRes, error)
	// Logout implements logout operation.
	//
	// Log out user.
	//
	// POST /api/v1/auth/logout
	Logout(ctx context.Context) (LogoutRes, error)
	// PostData implements postData operation.
	//
	// Post some data.
	//
	// POST /api/v1/data
	PostData(ctx context.Context, req *DataRequest) (PostDataRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
