openapi: 3.0.3
info:
  title: Base App API
  version: 1.0.0
  description: A sample API for a Go application with Clean Architecture.

paths:
  /api/v1/auth/login:
    post:
      summary: Authenticate user
      operationId: login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /api/v1/auth/logout:
    post:
      summary: Log out user
      operationId: logout
      tags:
        - Auth
      responses:
        '200':
          description: Successful logout
        '500':
          description: Internal Server Error

  /api/v1/auth/me:
    get:
      summary: Get current user info
      operationId: getMe
      tags:
        - Auth
      responses:
        '200':
          description: Current user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /api/v1/data:
    post:
      summary: Post some data
      operationId: postData
      tags:
        - Data
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataRequest'
      responses:
        '201':
          description: Data created successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  /api/v1/catalog:
    get:
      summary: Get catalog items
      operationId: getCatalog
      tags:
        - Catalog
      security:
        - cookieAuth: []
      responses:
        '200':
          description: A list of catalog items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CatalogItem'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session

  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        created_at:
          type: string
          format: date-time

    DataRequest:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
      required:
        - key
        - value

    CatalogItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        disabled:
          type: boolean

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message